### ISSUE TITLE
ZCRMRestClient doesn't exist

### ISSUE THREAD

**Issue by dimizago** [thomas-kl1/php-sdk-zoho-desk#1]
The ZCRMRestClient is a class of the original archived zcrm sdk and you have to require it in order for this sdk to work

**Comment by thomas-kl1** [comment]
Hi @dimizago do you have a trace of the error?
I can't find anything related to this class in the code

**Comment by thomas-kl1** [comment]
@dimizago what version of this package have you used in your test?

**Comment by dimizago** [comment]
In your example you have this line

`ZCRMRestClient::initialize($configBuilder->create());`

I get an error from PHPStorm that this Class doesn't exist, and by searching at the repos files it doesn't exist somewhere. 

The only repo that has this class is the original zcrm sdk which is archived.

**Comment by thomas-kl1** [comment]
My bad, that's right, I didn't updated the documentation and samples, let me fix this!

**Comment by thomas-kl1** [comment]
@dimizago I've updated the sample code and the README.md:

https://github.com/thomas-kl1/php-sdk-zoho-desk/blob/master/docs/sample/code/index.php

I hope I've didn't missed anything!
