### ISSUE TITLE
Zoho\OAuth\Utility\ZohoOAuthConstants not Found 

### ISSUE THREAD

**Issue by dimizago** [thomas-kl1/php-sdk-zoho-desk#2]
Hello, 

I get this error message when trying to initialize the SDK.

`Uncaught Error: Class 'Zoho\OAuth\Utility\ZohoOAuthConstants'`

I get this here
`tklein\php-sdk-zoho-desk\src\Client\ConfigProviderBuilder.php on line 37`

Did you encounter this issue or am I using something wrong?

Thanks!

**Comment by thomas-kl1** [comment]
@dimizago how did you installed the package and how are you using it?

This sdk must installed through composer, then you have to use the composer autoloader to get class loaded as expected.

**Comment by dimizago** [comment]
I'm following the documentation line by line. 

I installed the package through composer and I have the class on autoloader. 

I am using Slim 4

**Comment by thomas-kl1** [comment]
Hi @dimizago 

Indeed there was an issue in the composer autoloader configuration, you check the changes here:

https://github.com/thomas-kl1/php-sdk-zoho-desk/compare/2.1.1...3.0.0

Also as I didn't touch the zoho oauth base package, there were still a dependency with the zoho crm/utility package in the logger class. I've fixed it and you can declare a constant LOGGER_PATH to store the zoho/oauth logs in the location of your choice.

**Comment by thomas-kl1** [comment]
Btw if you still want to use the original package of zoho/oauth which also include zoho/crm (https://github.com/zoho/zcrm-php-sdk), please use the strict version of 2.0.0

Maybe in future I'll get rid of the zoho/oauth and write a proper oauth initializer
