### ISSUE TITLE
How to generate Access Token?

### ISSUE THREAD

**Issue by stefnats** [thomas-kl1/php-sdk-zoho-desk#4]
Sorry, if this too obvious but i'm not seeing it.

How would the code look like to connect this sdk to zoho desk?

I'm trying this:

```php
use Zoho\Desk\Api\Metadata;
use Zoho\Desk\Client\ConfigProviderBuilder;
use Zoho\OAuth\ZohoOAuth;

$configBuilder = ConfigProviderBuilder::getInstance();
$configBuilder->setClientId(/* Client ID */)
    ->setClientSecret(/* Client Secret */)
    ->setRedirectUrl(/* Redirect Url */)
    ->setCurrentUserEmail(/* User Email */)
    ->setApiBaseUrl(/* API Endpoint by region */)
    ->setApiVersion(Metadata::API_VERSION)
    ->setOrgId(/* Org ID */)
    ->setIsSandbox(/* Sandbox Status */)
    ->setAccountsUrl(/* Accounts Url */)
    ->setTokenPersistencePath(/* Persistence Path */);

// Add php code if the zcrm_oauthtokens.txt to create the file if it does not already exists.

ZohoOAuth::initialize($configBuilder->create()->get());
ZohoOAuth::getClientInstance()->generateAccessToken($grantCode);
```

But i don't see what `$grantCode` should be. 
What i've done so far:

I've registered my Client (got ID & Secret), set the Endpoint (EU), Org ID, etc. 
What do i have to do next?

**Comment by thomas-kl1** [comment]
Hi @stefnats 

You should connect to https://api-console.zoho.eu/ (or any other .domain depending of the region subscription, as .com, .in, .com.au..) and create or use the self-client api provider. You will then be able to generate a grant code, to use in few minutes. Be careful and give the right scope permissions depending of your needs.

https://www.zoho.com/crm/developer/docs/api/v2/scopes.html
https://desk.zoho.com/DeskAPIDocument#OAuthScopes

I don't have access anymore to a ZOHO API Client, so if you have an issue with the library, feel free to reach me directly :)

**Comment by stefnats** [comment]
Ah thanks! That wasn't clear from the docs.

However the HTTP Result (in `ZohoOAuthClient.php` line 148) is this:

```html
HTTP/1.1 401 
Server: ZGS
Date: Mon, 26 Apr 2021 06:34:53 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 2656
Connection: keep-alive
Set-Cookie: d4bcc0a499=7d791220fd4cf7909b899dac13d8da8c; Path=/
X-Content-Type-Options: nosniff
X-XSS-Protection: 1
Set-Cookie: iamcsr=c3caf65d-9335-4438-9534-65337c06e0b1;path=/;SameSite=None;Secure;priority=high
Set-Cookie: _zcsr_tmp=c3caf65d-9335-4438-9534-65337c06e0b1;path=/;SameSite=Strict;Secure;priority=high
Pragma: no-cache
Cache-Control: private,no-cache,no-store,max-age=0,must-revalidate
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
Set-Cookie: JSESSIONID=B9C94C411B61A9E8E196FDE908DBF308; Path=/; Secure; HttpOnly
vary: accept-encoding






















<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link
\thref="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700"
\trel="stylesheet">

</head>
<style>
body {
\twidth: 100%;
\tfont-family: 'Open Sans', sans-serif;
\tmargin: 0px;
}

.container {
\tdisplay: block;
\twidth: 70%;
\tmargin: auto;
\tmargin-top: 120px;
}

.zoho_logo {
\tdisplay: block;
\tmargin: auto;
\theight: 34px;
\tmax-width: 200px;
\twidth: 100px;
\tbackground: url("https://static.zohocdn.com/iam/v2/components/images/zoho.23e9f1386f4d8aedfdf49c511c2b63dd.png") no-repeat transparent;
\tbackground-size: auto 100%;
\tmargin-bottom: 40px;
\tbackground-position: center;
}

.error_img {
\tdisplay: block;
\theight: 300px;
\tmargin-bottom: 40px;
\twidth: 100%;
}

.raodblock {
\tbackground: url(https://static.zohocdn.com/iam/v2/components/images/roadblock.94f70c680f7cb06f480b33f958d02820.png) no-repeat transparent;
\tbackground-size: auto 100%;
\tbackground-position: center;
}

.heading {
\tdisplay: block;
\ttext-align: center;
\tfont-size: 24px;
\tmargin-bottom: 10px;
\tline-height: 34px;
\tfont-weight: 600;
}

.discrption {
\tdisplay: block;
\twidth: 500px;
\tmargin: auto;
\ttext-align: center;
\tfont-size: 16px;
\tmargin-bottom: 10px;
\tline-height: 24px;
\tcolor: #444;
}

@media only screen and (-webkit-min-device-pixel-ratio: 2) , only screen and (
\t\tmin--moz-device-pixel-ratio: 2) , only screen and (
\t\t-o-min-device-pixel-ratio: 2/1) , only screen and (
\t\tmin-device-pixel-ratio: 2) , only screen and ( min-resolution: 192dpi)
\t\t, only screen and ( min-resolution: 2dppx) {
\t.raodblock {
\t\tbackground: url(https://static.zohocdn.com/iam/v2/components/images/roadblock@2x.91374380df32097beed18c88a3d287f2.png) no-repeat transparent;
\t\tbackground-size: auto 100%;
\t\tbackground-position: center;
\t}
}

@media only screen and (max-width: 420px) {
\t.container {
\t\twidth: 90%;
\t\tmargin-top: 50px;
\t}
\t.discrption {
\t\twidth: 100%;
\t}
\t.error_img {
\t\tdisplay: block;
\t\tmax-width: 340px;
\t\tbackground-size: 100% auto;
\t\tmargin: auto;
\t\tmargin-bottom: 40px;
\t}
\t.heading {
\t\tdisplay: block;
\t\ttext-align: center;
\t\tfont-size: 20px;
\t\tmargin-bottom: 10px;
\t\tline-height: 30px;
\t\tfont-weight: 600;
\t}
\t.discrption {
\t\tdisplay: block;
\t\tmargin: auto;
\t\ttext-align: center;
\t\tfont-size: 14px;
\t\tmargin-bottom: 10px;
\t\tline-height: 24px;
\t\tcolor: #444;
\t}
}
</style>

<body>
\t<div class="container">
\t\t<div class="zoho_logo"></div>
\t\t<div class="error_img raodblock"></div>
\t\t<div class="heading">An error occurred.</div>
\t\t<div class="discrption">An error occurred while processing your request.<br> Please try again later.
\t\t</div>
\t</div>
</body>
</html>
```

I think i'm doing something wrong here. So i have a few questions:

- What should be the Redirect URI?
- Where do i find the Org ID (i used the one from the CRM?!)
- Current User E-Mail is the one i'm using to login, right?

**Comment by thomas-kl1** [comment]
The "Redirect URI" is part of the standard for oauth request processing, but is almost never used, you can pass a dummy url.

The Org ID should be available in your zoho desk account, in the API section (https://www.cubeyogi.com/Zoho%20Knowledge%20Base/Zoho%20Desk%20Knowledge%20Base/Q-406/getting-organization-id-orgid-in-zoho-desk)

The current user e-mail should be the dedicated user for your api integration, it could be yours or something more generic such as zoho.desk@my-company.com . This is the user which have created the grand code and self-client integration.

Sadly the Zoho errors are not really verbose..

**Comment by stefnats** [comment]
Hey @thomas-kl1 thanks for the info.

Seems like i receive a valid access token, however retrieving the user email (as mentioned in `ZohoOAuthClient.php` in line 148) does not work. I'm only granting scope `Desk.tickets.ALL`.

I have two approaches, maybe you have something to add

1. Zoho changed to a V2 API which might not support that call?
2. I need to add a scope that allows retrieving user data?

*EDIT*: Forgot to mention the URL that was called to retrieve the email  was `https://accounts.zoho.eu/oauth/user/info`

**Comment by thomas-kl1** [comment]
Hi yes there is a mandatory scope to add in order to be able to use refresh token calls:

aaaserver.profile.READ

**Comment by stefnats** [comment]
That did the trick!

Thanks so much @thomas-kl1 ! I appreciate it.

**Comment by thomas-kl1** [comment]
@stefnats I'll update the documentation with this ticket :)
