### ISSUE TITLE
Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by ca-dsgn** [thomas-kl1/php-sdk-zoho-desk#6]
I am currently facing this fatal error - I am not sure how to solve this:

```
 Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in engine/vendor/tklein/php-sdk-zoho-desk/lib/zoho/oauth/ZohoOAuthClient.php:128
```

This is my code:

```php
$client_id = "";
$client_secret = "";

$redirect_url = $domain."/engine/zoho.php";

$configBuilder = ConfigProviderBuilder::getInstance();

$configBuilder->setClientId($client_id)
  ->setClientSecret($client_secret)
  ->setRedirectUrl($redirect_url)
  ->setCurrentUserEmail("mail@test.com")
  //->setApiBaseUrl(/* API Endpoint by region */)
  ->setApiVersion(Metadata::API_VERSION)
  ->setOrgId("123456")
  //->setIsSandbox(/* Sandbox Status */)
  //->setAccountsUrl(/* Accounts Url */)
  ->setTokenPersistencePath("engine");

$config = $configBuilder->create();
$gateway = new Gateway($config);

// Optional: if you need to register the token first
ZohoOAuth::initialize($config->get());
ZohoOAuth::getClientInstance()->generateAccessToken("xxx");

try {

  $ticketDataObject = $gateway->getOperationPool()->getReadOperation('tickets')->get(851);
  
  print_r($ticketDataObject);

} catch (CouldNotReadException $e) {

  print_r($e->getMessage());
}
```

I commented the lines setApiBaseUrl, setIsSandbox and setAccountsUrl out, beause I think I don't have to set those values, or do I? If so, what are the recommended values here?

Thank you in advance for your support.

Best,
Christian

**Comment by ca-dsgn** [comment]
Ok, solved my issue by myself. I am leaving this comment if anybody might this find helpfull:

I uncommented the lines

```php
->setApiBaseUrl("desk.zoho.com/api")
->setAccountsUrl("https://accounts.zoho.com")
```

And used the US values (even if I am using zoho from Europe, Germany).

I also used this scope for creating the grantCode (Create here: https://api-console.zoho.com): 
```
aaaserver.profile.READ,Desk.tickets.ALL
```
Using this scope, I can create the token and also CRUD tickets.

A list of the available scope values for Zoho Desk can be found here:
https://desk.zoho.com/DeskAPIDocument#OauthTokens#UsingOAuthtokenAPI

**Comment by thomas-kl1** [comment]
hi @ca-dsgn 

Yes actually you must set all options before you create the config from the builder.
The base url actually depends of where the licence for Zoho has been purchased.

At least the `aaaserver.profile.READ` is mandatory across all Zoho APIs for the oauth token generation, then you'll have to add the proper scope you need, according to the grant code you have generated (they to match). I'll add the link you provided to the readme, thank you for the feedback! :+1:
